version: '3'
services:
  web:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - .:/code
    command: flask run --host=0.0.0.0
    environment: 
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
  db:
    image: 'mongo'
    container_name: 'mongo-db'
    volumes:
      - /tmp/mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
  local:
    build:
      context: .
      dockerfile: local.Dockerfile
    volumes:
      - .:/code
    command: tail -f /dev/null

